version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: depth-es
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - escap-vol:/usr/share/elasticsearch/data

  kibana:
    image: kibana:latest
    container_name: depth-kibana
    ports:
      - "5601:5601"

volumes:
  escap-vol:
    external:
      name: elastic-depth
