mappings:
  poi:
    properties:
      keyword:
        type: string
      location:
        type: geo_point
      q_location:
        type: geo_point
      placeid:
        type: string
      ts:
        type: date
